# Generated by Django 6.0 on 2026-01-12 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('government_id', models.FileField(upload_to='delivery_docs/')),
                ('driving_license', models.FileField(upload_to='delivery_docs/')),
                ('vehicle_document', models.FileField(upload_to='delivery_docs/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='delivery_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
