# Generated by Django 6.0 on 2026-03-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_delivery_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute_type',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('shoes', 'Shoes'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
