# Generated by Django 6.0 on 2026-03-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attribute_type',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('shoes', 'Shoes'), ('none', 'Others')], default='none', max_length=20),
        ),
    ]
